name: Events workflow dispatch
on: 
  pull_request:
      types:
        - opened
  push:
    paths-ignore:
      - .github/**
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependancies
        run: npm ci
      - name: Run tests
        run: npm test
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: install dependancies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy 
        run: echo "Deploying application....."
